version: '3.1'

services:
  demo-rabbit:
    container_name: demo-rabbit
    image: rabbitmq:3.10.20-management
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

#  demo-producer:
#    container_name: demo-producer
#    image: demo-producer
#    #    environment:
#    #      - DB_SERVER=db
#    ports:
#      - "8080:8080"
#    build:
#      context: ./demo-producer
#      dockerfile: Dockerfile
##    depends_on:
##      - db
#
#  demo-consumer:
#    container_name: demo-consumer
#    image: demo-consumer
##    environment:
##      - DB_SERVER=db
#    ports:
#      - "8081:8081"
#    build:
#      context: ./demo-consumer
#      dockerfile: Dockerfile
##    depends_on:
##      - db

networks:
  rabbitmq_go_net:
    driver: bridge

#volumes:
